### PR TITLE
Add touchstart handler to Sidebar

### PR DESCRIPTION
**Pull request by Thomazella**
**What kind of change does this PR introduce?**

Adds event handlers to Sidebar.tsx

**Did you add tests for your changes?**

Will do. It decreased coverage.

**Does this PR introduce a breaking change?**

Probably will.

### CODE REVIEW

**Comment by diegohaz** [comment]
I don't know if that's the behavior we want. If one simply slides to right, down or up, the element shouldn't hide (if `align="left"`).

It probably needs more research. We have to understand better how it works on native apps and try to mimic the same behavior. I've never seen that being done on the web though. :/

Also, note that, if this isn't an optional feature (activated by a prop, for example), it's a breaking change, since it could be an undesired behavior.

**Comment by Thomazella** [comment]
That's ok, pushed to get some feedbacks. I'll add it as WIP

**Comment by diegohaz** [comment]
Some references:

http://ascott1.github.io/bigSlide.js/
https://slideout.js.org/ (this one is very good)

**Comment by renatorib** [comment]
> I don't know if that's the behavior we want. 

What is the behavior you want?
Maybe I can help. I've been doing [experiments](https://codesandbox.io/s/oxm5rlwnrq) with touch/swipe some days ago

**Comment by diegohaz** [comment]
@renatorib I talked with @Thomazella on Slack about it and we both agreed that the usability on https://slideout.js.org/ (must simulate or run on mobile to see the swipe effect) is pretty much what we want.

We're kind of stuck here, so any help would be really appreciated. 

Your experiment looks really ingenious. Are you aiming to build something with it?

**Comment by Thomazella** [comment]
I'm focused on another project, which should be done in a few days, but I was working on a slideout inspired component. @renatorib should definitely help though. :D You could go ahead and work on it while I'm busy and when I'm free, I can contribute.

**Comment by Thomazella** [comment]
closing as @renatorib has taken this over. :)

**Pull request closed without merging**
