### PR TITLE
feat: New `use` prop/method

### LINKED ISSUE #226: Incompatibility with `as` prop in styled-components v4 (RFC)
## Background
styled-components [just released V4](https://medium.com/styled-components/announcing-styled-components-v4-better-faster-stronger-3fe1aba1a112) bringing a lot of great new features 🎉 

However, among these new features they added their own [polymorphic `as` prop](https://www.styled-components.com/docs/api#as-polymorphic-prop) that looks very similar to [the one in reakit](https://reakit.io/guide/as), but they behave in subtly different and incompatible ways. 

The `as` prop provided by components in reakit allow you compose together the behaviors of several components at once:

```jsx
import { Button } from 'reakit';
import styled from 'styled-components';

const MyButton = styled(Button)`
  background-color: red;
`

<MyButton as="a">Hello</MyButton>

// renders <a role="button" tabindex="0">Hello</a>
```

In this example the resulting HTML is an a tag with all the attributes of the `Button` component.

Compare that to when you use the `as` prop from a styled-components component it will replace which component is rendered rather than composing them.

So in the example above, the `Button` component would get ignored resulting in:

```jsx
<a>Hello</a>
```

## Problem

his presents a legitimate compatibility problem for reakit going forward. Additionally it presents a lot of possible confusion for newcomers. It would likely and totally understandable if when people see the reakit `as` prop, they would just assumed it would work like the native styled-components prop.

## Possible solution

Rename the reakit prop to something else.

A couple proposed options are:

- `with`
- `uses`
- `use`
- `compose`

I think this would clear up any possible confusion and also is a better description of how the prop behaves, given that it can also take an array of components:

```jsx
<MyComponent with={[Button, "a"]}>Hello</MyComponent>
<MyComponent uses={[Button, "a"]}>Hello</MyComponent>
<MyComponent use={[Button, "a"]}>Hello</MyComponent>
<MyComponent compose={[Button, "a"]}>Hello</MyComponent>
```

The enhancer should also be renamed:

```js
composeWith([Button, "a"])(MyComponent) // with is a reserved word
uses([Button, "a"])(MyComponent)
use([Button, "a"])(MyComponent)
compose([Button, "a"])(MyComponent)
```

Other ideas welcome:

Please respond with any other ideas for solutions or general thoughts on this proposal.

### PR DESCRIPTION
**Pull request by diegohaz**
Closes #226

Preparing the ground to styled-components v4

- [x] Replace `as` by `use`
- [x] Update website
- [x] Remove dependency on `hoist-non-react-statics`
- [x] Fix website footer
- [x] Pass missing props to `BoxProps`
- [x] Update docs
- [x] Figure out a way to ease the migration (maybe a regex to find and replace)
- [x] Ref
- [x] Cleanup all component props

### BREAKING CHANGES

- `as` has been replaced by `use`.

  Due to inconsistencies between the new styled-components v4 `as` prop and Reakit's one, we decided to introduce a new feature called `use` as a replacement. It has a few differences from the old `as`:

  ```diff
  - import { as } from "reakit";
  + import { use } from "reakit";

  - const ButtonDiv = as("div")(Button);
  + const ButtonDiv = use(Button, "div");

  - const ButtonDiv = Button.as("div");
  + const ButtonDiv = use(Button, "div");

  - const ButtonLinkDiv = as([Link, "div"])(Button);
  + const ButtonLinkDiv = use(Button, Link, "div");

  - const ButtonLinkDiv = Button.as([Link, "div"]);
  + const ButtonLinkDiv = use(Button, Link, "div");

  - <Button as="div" />
  + <Button use="div" />

  - <Button as={[Link, "div"]} />
  + <Button use={[Link, "div"]} />
  ```

  It has been released as a separate package. For more information, see [Reuse](https://github.com/diegohaz/reuse).

- `areas`, `columns` and `rows` props on `Grid` have been replaced by `templateAreas`, `templateColumns` and `templateRows`.

  ```diff
    <Grid
  -  areas="a b c"
  +  templateAreas="a b c"
  -  columns="1fr 60px auto"
  +  templateColumns="1fr 60px auto"
  -  rows="auto"
  +  templateRows="auto"
    />
  ```

### CODE REVIEW

**Comment by diegohaz** [comment]
Yes. Actually, replace them like in the examples in the PR description.

**Comment by diegohaz** [comment]
It turns out that we have to keep wrapping components with `use` because of TypeScript (in JS, one could just use defaultProps).

**Comment by diegohaz** [comment]
I'm going to merge this as it is so I can start working on upgrading styled-components. If you guys see anything wrong on the code, please let me know.

**Comment by diegohaz** [comment]
I'm going to merge this as it is so I can start working on upgrading styled-components. If you guys see anything wrong on the code, please let me know.

**Comment by diegohaz** [comment]
I'm going to merge this as it is so I can start working on upgrading styled-components. If you guys see anything wrong on the code, please let me know.

**Comment by diegohaz** [comment]
I'm going to merge this as it is so I can start working on upgrading styled-components. If you guys see anything wrong on the code, please let me know.

**Comment by diegohaz** [comment]
GitHub is really unstable! Will merge it later.

**Comment by Thomazella** [comment]
awesomeee 🎉

**Pull request merged**
