### PR TITLE
Remove rollup-plugin-filesize

### PR DESCRIPTION
**Pull request by Andarist**
This is a followup to the [latest rollup-related PR](https://github.com/reakit/reakit/pull/168#issuecomment-410487000).

⚠️  I have not tested this code thoroughly, just assembled this PR to see if this helps CI build times at all.

Theory is that rollup should be able to reuse the work putted into transforming, chunking etc esm & cjs formats and use that to finalize both. So this should give significant time boost.

### CODE REVIEW

**Comment by Andarist** [comment]
It has no difference on build time - which is slightly surprising to me 🤔 Gonna leave it as open, you might want to incorporate some of the changes into the library (dropping lodash maybe?).

Slow build times need investigation though, not sure what we can do though about it. Maybe rollup team will have some insight into this.

**Comment by diegohaz** [comment]
Getting rid of lodash is good. Thank you so much for your help, @Andarist 🙏

I'm gonna try some things here too.

**Comment by diegohaz** [comment]
It seems that `rollup-plugin-filesize` was the problem. 😱

**Comment by Thomazella** [comment]
> Getting rid of lodash is good.

Shoudn't we do this on another PR? Benchmark things a bit before and after...

**Comment by Andarist** [comment]
Oh damn, also thought about removing it to check things out without but havent pursued that idea, great finding!

As you see my removal of lodash has broken tests 😂 but as I said - I haven't really tested it, wanted only to remove it so I could merge cjs & esm configs. I believe it should be fairly easy to tweak this code to make it actually work - I won't have time to do it though, so if you want to pursue it you can revert my 2 latest commits and pick the work up, or just copy-paste it onto some new branch - or just close this & create issue about removing lodash 😉

**Comment by Thomazella** [comment]
Thanks again @Andarist for helping us on this 😄

**Pull request merged**
