### PR TITLE
Added rollup-plugin to populate gitignore file with proxy-directories

### PR DESCRIPTION
**Pull request by adriankremer**
By generating the proxy directories for the reakit library all the generated files a not handled by .gitignore.

I have pulled the makeProxies script and created a rollup plugin called `rollup-plugin-proxy-directories` which also takes the files aka. publicFiles and generates a .gitignore file or populates it with the proxied modules.

This plugin i have used to replace the makeProxies script and to generate a .gitignore file listing all the modules.

https://github.com/adriankremer/rollup-plugin-proxy-directories

### CODE REVIEW

**Comment by diegohaz** [comment]
Hey @adriankremer. Thank you for this package. ❤️

I'll take a better look into it. By a first glance, I would say it should be more generic, like not hard coding `../ts`, `.../es`, `.../dist`.

I'm working on new scripts for v1. Besides the issue above, they also address the use case of deep proxies (like `/box/useBoxProps/package.json`). See: https://github.com/reakit/reakit/blob/135d9ae4a40d7cb8e953f7ebcefb31febdd92a0a/scripts/build/utils.js

**Comment by adriankremer** [comment]
Hi @diegohaz, cool!
i like the deep proxy approach. 
For the next version i'm going to use the main, module & typings prop from the used package to be more generic.
In the future i would also like to put together the proxy directories per configuration (globbing or something else) and to clean them also by rollup.

**Comment by adriankremer** [comment]
Hey @diegohaz nice job on that!!

i've updated the rollup plugin (v1.1.0) to support deep-proxies and build-dir resolving.
Also the gathering of public-files is now part of the plugin and it can be used without configuration.

A downside is, that you cannot access the cleaning of public files at the moment and for a plugin it would not be semantically correct to export these functions.

**Comment by diegohaz** [comment]
The current build scripts are too specific to Reakit, and they often need to be updated. So I guess it's better keep the source code here. Anyway, thank you for your work @adriankremer.

**Pull request closed without merging**
