### PR TITLE
Upgrade to React 17

### PR DESCRIPTION
**Pull request by tom-sherman**
Opening so we can easily inspect the docs site with React 17

### CODE REVIEW

**Comment by tom-sherman** [comment]
Gah, yarn timed out? Lame...

**Comment by tom-sherman** [comment]
Clearly this is a sign from a higher being to go to bed and try again in the morning 🤷‍♀️

**Comment by tom-sherman** [comment]
Oh DAMN, the dependencies have been added from the wrong registry.

**Comment by diegohaz** [comment]
That's a bummer. I was debugging this locally and I had to use Yarn resolutions to see it in Storybook. :(

I currently have 4 failing tests, will push my changes to this branch tomorrow.

But I think the cron CI (that's explicitly installing `react@next`) is working well. We just need to include `react-test-renderer` there, right?

**Comment by tom-sherman** [comment]
> But I think the cron CI (that's explicitly installing react@next) is working well. We just need to include react-test-renderer there, right?

@diegohaz you're right, I'll ammend the workflow now.

**Comment by tom-sherman** [comment]
It's published aaaaaaan the docs site is completely broken 😆

https://deploy-preview-707--reakit.netlify.app/

**Comment by diegohaz** [comment]
> It's published aaaaaaan the docs site is completely broken 😆
>
> https://deploy-preview-707--reakit.netlify.app/

Looks like it's a React version mismatch. Some components may be using React 16, and others React 17.

**Pull request closed without merging**
