### PR TITLE
feat: improve separator aria return

### LINKED ISSUE #721: [Separator] Return role and aria-orientation when the element is not `hr`
## 🚀 Feature request

Only return `Role: seperator` when the element is not `hr` tag and `Orientation: vertical` when the orientation is vertical.

Adding them when the tag is `hr` and in horizontal orientation is redundant IMO.

### Motivation

Seperator `<hr />` by default has `Role: seperator` and `Orientation: horizontal`.

Resizer

### Possible implementations

We check the `as` prop, if it's other than `hr`, we return `Role: seperator` and the orientation is `vertical` when return `Orientation: vertical`

### PR DESCRIPTION
**Pull request by navin-moorthy**
Adds extra checks to Separator Component as discussed in the below issue,
Closes #721 

Added Storybook example to demonstrate the behaviour,

Path: [packages/reakit/src/Separator/__examples__/Seperator/index.tsx](https://github.com/reakit/reakit/compare/next...feat/separator-update?expand=1#diff-9704763ecd7170b58cbe7b2e5da305a1)

image

image

**How to test?**

Run `yarn storybook` to see the `Separator Example` story and test it.
Added tests myself -> [packages/reakit/src/Separator/__tests__/Separator-test.tsx](https://github.com/reakit/reakit/compare/next...feat/separator-update?expand=1#diff-3a64a6bea74946a412197176a31a3141)

**Does this PR introduce breaking changes?**

May be 🤔 , used `as` to acheive the behaviour.
Passed down `as` from `createComponent` to `useHook`

### CODE REVIEW

**Comment by navin-moorthy** [comment]
@diegohaz I tried hard to type `as` prop in `createComponent` but failed.

Kindly help me typing `as` for `useHook`
image

Also, I have took my time to try out passing different custom elements/components/nested-components by writing checks based on `as`,
Seems we can achieve the same results by using `ref`, since in the end all the elements as converted to html string tags.

Let me know your view on this !!

**Comment by diegohaz** [comment]
Thank you for working on this @navin-moorthy!

Regarding the TypeScript error, I don't know if this is going to solve the problem. But you can try this:

1. Add the `as` prop type to `RoleOptions` (`Role/Role.ts`).
2. Run `yarn keys`.
3. Remove the `as` prop from the argument on `useHook` and pass it to `splitProps` instead, like this:
    ```js
    const [options, htmlProps] = splitProps({ as, ...props }, keys);
    const { wrapElement, ...elementProps } = useHook(options, {
    ```

This should fix the problem inside the hook when you do `const { as } = options;`, but I'm not sure it will fix the type errors on `createComponent.ts`. We may have to make `O` extend from something. I don't know.

Besides that, is `isString` necessary? Couldn't it be just `const notHr = as !== "hr"`?

**Comment by navin-moorthy** [comment]
Thanks for providing your suggestions @diegohaz .

Working more on this made me realize that its not possible to find the final element using `as`.
Using `as` fails when the custom component has an `as` attribute which is `hr`.

I fellback to how we determine the native element and pushed the changes.
Let me know your thoughts.

**Comment by navin-moorthy** [comment]
@diegohaz Hope you haven't missed this PR & kindly review it when you are free.

**Pull request closed without merging**
