### PR TITLE
Add state prop with backward compatibility

### PR DESCRIPTION
**Pull request by david-szabo97**
This PR tries to implement this issue: https://github.com/reakit/reakit/issues/744

Allow the use of `state` prop instead of object spreading. 

## How it works

Since all components are created with `createComponent`, this implementation modifies this function to allow either `state` object or `state` object spreading.

`createComponent` uses two functions that are related to the props: `splitProps` and `propsAreEqual`.

If `splitProps` finds a `state` **plain object** in the `props` then it returns the `state` object instead of using the `keys` to split the props. If the `props` doesn't have a `state` that is **plain object** then it split the props using the `keys`.

Since we are trying to move the `state` into the `state` object, `propsAreEqual` need to make sure it takes the `state` object into account. In our case, we have a new higher-order function called `normalizePropsAreEqual` which takes care of normalizing the `prev` and `next` inputs. It works by checking for the existence of `state` **plain object** property on both `prev` and `next` object. If it exists on both objects then it spreads the `state` into the props. Which means it's fully backward compatible with all of our existing `propsAreEqual` functions. 

## Example

```jsx
<MenuButton state={menu}>Preferences</MenuButton>
<Menu state={menu} aria-label="Preferences">
        <MenuItem state={menu}>Settings</MenuItem>
        <MenuItem state={menu}>Extensions</MenuItem>
        <MenuItem state={menu}>Keyboard shortcuts</MenuItem>
</Menu>
```

## Does this PR introduce breaking changes?

No, it is supposed to be 100% backward compatible.

### CODE REVIEW

**Comment by diegohaz** [comment]
Wow! Amazing work @david-szabo97! I didn't realize we could add this feature at the system level 😮

I made a quick test in the website preview passing `state={state}` to some components and things seem to work well. I'll do a more thorough test later this week and better read the code. Is there something you think needs more attention (maybe the Radio/Checkbox components, TypeScript etc.)?

**Comment by david-szabo97** [comment]
Components with `state` props are handled correctly. At least, I took that into account and hopefully it works well. This is the main reason for checking for `isPlainObject`. If we don't have any component that uses a `state` prop with an object, then we are good to go.

One thing that worth mention is we lost the `required` props type checking. Since we need to make all the properties optional to make sure we can use `state` prop. I'm not sure if it's possible to fix it: https://github.com/reakit/reakit/pull/771/files#diff-a67169273d617321db1694dc0fc3bb29d8aa00871af6b76345492d078b09f6abR56-R61

A bit off-topic but still related to this: the code became more complex 😄 What's your plan for the code for v2? Are we going to work in a separate branch where we remove all the code that will be unneeded in v2? I'm not sure what would be the best, since we also need to make sure that whatever we do in v1 needs to be in v2.

**Comment by david-szabo97** [comment]
Just added a few comments and a minor change. The code is ready from my side 🙂 I did manual tests and I found no issues so far. Automated tests are passing 🥳

**Comment by diegohaz** [comment]
> A bit off-topic but still related to this: the code became more complex 😄 What's your plan for the code for v2? Are we going to work in a separate branch where we remove all the code that will be unneeded in v2? I'm not sure what would be the best, since we also need to make sure that whatever we do in v1 needs to be in v2.

Yeah, the plan is to work on the [`v2` branch](https://github.com/reakit/reakit/tree/v2) (just created it). I'll create an issue explaining better my ideas for v2, but I would like to get rid of deprecated stuff and the `reakit-system-*` packages, which were an experiment that hasn't had any progress on v1.

I also think we can simplify a lot the code. For example, I'd like to write a component like this:
```ts
export const useComposite = createHook<CompositeOptions>(({ state, ...props }) => {
  ...
  return props;
});

export const Composite = createComponent<CompositeOptions>((props) => {
  props = useComposite(props);
  return createElement("div", props);
});

export type CompositeOptions<T extends As = "div"> = TabbableOptions<T> & {
  state?: CompositeState;
};
```

From what I've been experimenting with so far, this works well: https://codesandbox.io/s/substate-test-fxhir?file=/src/components/Button/Button.ts

**Review by diegohaz — APPROVED** [review]
It's working great! Thanks for the awesome work @david-szabo97! :)

I'm merging it into the `next` branch so this can be released as alpha and people can test it.

**Pull request merged**
