### PR TITLE
chore: Run example tests on BrowserStack

### PR DESCRIPTION
**Pull request by tom-sherman**
Todo:

- [ ] Investigate running locally
- [ ] CI and CI failure reporting
- [ ] Swap out personal creds for Reakit's

### CODE REVIEW

**Comment by tom-sherman** [comment]
@diegohaz Could you please check out this branch and run `npx karma start` to see if you get the same error I'm seeing? You may need to add a `.env` file with `BROWSERSTACK_USERNAME` and `BROWSERSTACK_USERNAME` values.

It's [this error from 2016](https://github.com/karma-runner/karma-browserstack-launcher/issues/69), but reinstalling node_modules doesn't help for me.

**Comment by diegohaz** [comment]
Thanks @tom-sherman! I'll have a look at it. By just reading the code though I'm not sure we'll be able to run the same tests on jsdom and in the browser.

It would be great if it worked, but I've never tested `reakit-test-utils` in a browser.

So maybe we'll have to create separate test files for e2e. But we don't really need to test everything.

**Comment by tom-sherman** [comment]
@diegohaz yeah I think you're right, looks like the tests are going to need migrating to a different assertion library.

**Comment by tom-sherman** [comment]
Do you think there's value in having the example tests in both Jest and karma/BrowserStack?

**Comment by diegohaz** [comment]
> Do you think there's value in having the example tests in both Jest and karma/BrowserStack? As in two separate test files

Yes! And they would probably have different tests. For example, we can't test with jest if Button gets focused on click on Safari/Firefox on Mac, or if Composite works on IE11. I'm not sure if BrowserStack lets us do this, but it would be nice! :)

So I think the strategy would be testing in the browser only those things we can't do within JSDOM.

**Comment by diegohaz** [comment]
> @diegohaz Could you please check out this branch and run `npx karma start` to see if you get the same error I'm seeing? You may need to add a `.env` file with `BROWSERSTACK_USERNAME` and `BROWSERSTACK_ACCESS_KEY` values.
> 
> It's [this error from 2016](https://github.com/karma-runner/karma-browserstack-launcher/issues/69), but reinstalling node_modules doesn't help for me. So if you can also replicate it, I'll raise an issue there I guess.

I didn't see the error on MacOS.

**Comment by tom-sherman** [comment]
Just going to jot down my thinking with this, there are a lot of unknowns for me here so some of this may be obvious to E2E testing experts! 

## Orchestrate the browser like a real user

A key requirement, otherwise we may as well use something like Cypress and save ourselves a lot of work! This means triggering real clicks on elements, firing real keyboard events etc.

To do this we need to orchestrate the browser externally, probably using `selenium-webdriver`. See https://www.browserstack.com/docs/automate/selenium/getting-started/nodejs

This also prevents us from using karma-browserstack-launcher as well I think, as we need access to the webdriver instance to properly orchestrate the browser.

## Follow the Testing Library guiding principles

I personally think this is very important. See https://testing-library.com/docs/guiding-principles

Ideally we would also use one of the packages there, jasmine-dom looks suitable. I also think it's important to have a similar API to how the Jest tests are written as it will allow contributors to get up to speed more easily.

## Connecting these two peices together

So we have two competing techniques here. Orchestrating the browser requires code running outside of the browser using webdriver. On the other hand, `jasmine-dom` assumes that it is run inside a browser environment and needs direct access to the DOM elements it's matching against.

There are a few solutions here I think. One is to somehow inject the assertions into the browser via `executeScript`. It's likely we would need to do this anyway to actually render the components.

The other option is to rewrite the jasmine matchers using the selenium-webdriver API. What's good about this approach is that any `executeScript` usage that needs to happen (for example checking focused elements) is abstracted away from the tests, the tests would look very much like all of the other unit tests in the project.

**Comment by tom-sherman** [comment]
Here's my current line of thought.

I think the best way to render the tests is to use Storybook. It's already building all of the examples for us in an efficient manner, it would be a simple manner of orchestrating the browser to visit the correct example URL.

This approach requires deploying the Storybook somewhere, I'm assuming netlify is a good place for this. We would then just need a way to communicate the netlify URL back to the tests. I think this is the most complicated part of the whole plan.

The tests would then perform all of the assertions via the webdriver API on the Storybook-rendered examples.

**Comment by diegohaz** [comment]
Something that we also don't have right now, but which would be super cool, are mobile browsers tests. Do you know if it's possible?

**Comment by tom-sherman** [comment]
Yep I'm pretty sure it's possible. Browserstack lists a load of mobile browsers that we can use: https://www.browserstack.com/list-of-browsers-and-platforms/automate

**Comment by diegohaz** [comment]
Whoa, that's exciting!

By the way, regarding Storybook, it gets deployed on every pull request here: https://deploy-preview-733--reakit.netlify.app/storybook/

**Comment by tom-sherman** [comment]
Quick update, I don't think we're going to be able to use jest here because we need to maintain a single webdriver connection through all of the tests, this looks to be quite difficult with jest. We can still use the expect matcher API though with some other test harness (or write our own).

**Comment by diegohaz** [comment]
@tom-sherman Yeah, I imagined that it would be hard to use Jest for this. That's okay! If we can have something like `index-e2e.ts` next to our current example tests, it's already awesome!

Do you have any idea on how we should handle the credentials so it runs on PRs? I've added `BROWSERSTACK_USERNAME` and `BROWSERSTACK_ACCESS_KEY` secrets to the repo settings, but I'm not sure PRs created from forks will have access to them.

**Comment by diegohaz** [comment]
Screenshot of the repository secrets page with a note saying that secrets are not passed to workflows that are triggered by pull requests created from a fork

The "learn more" links to this page: https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

What's weird is that we're actually using `CODECOV_TOKEN` in workflows, and Codecov seems to work fine on PRs created from forked repos.

**Comment by diegohaz** [comment]
Well, it's not a blocker though. People will be invited after their first pull request anyway. If we need, we can also trigger browserstack locally.

**Comment by tom-sherman** [comment]
I'm guessing that's a security measure to stop randos `echo`ing all of the environment vars, makes sense!

**Comment by anuraghazra** [comment]
> Well, it's not a blocker though. People will be invited after their first pull request anyway. If we need, we can also trigger browserstack locally.

We can use the `pull_request_target` event to solve this issue, https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target

pull_request_target runs with the context of the base repository.

**Comment by tom-sherman** [comment]
Done a little more thinking this evening. The TypeScript compilation is currently not defined in this architecture, I'm thinking that we can parse these just-in-time using the TS compiler API either before the test suite is enqueued or before we execute it.

The only problem with this compile step is I'm not sure how we preserve stack traces. This is the most frustrating part about not using Jest, they've already solved a lot of hard problems in this space.


image

**Pull request closed without merging**
