### PR TITLE
Group stories by components

### PR DESCRIPTION
**Pull request by david-szabo97**
Fixes https://github.com/reakit/reakit/issues/774

Group stories by component to make it easier to navigate between stories. This lays the foundation which can be easily extended by adding more `.story.ts` files or editing the existing files.

Right now all the stories are grouped by components, open to any suggestions for changes.

**Screenshots**

image

**How to test?**

`yarn storybook`

**Does this PR introduce breaking changes?**

No

### CODE REVIEW

**Review by tom-sherman — CHANGES_REQUESTED** [review]
Can we remove the stories.js file?

Apart from that, LGTM - nice work!

**Review by tom-sherman — DISMISSED** [review]

**Comment by diegohaz** [comment]
Thanks for working on this, @david-szabo97! ❤️ 

One thing I noticed is that styles (imported css files) aren't being applied. For example, the accessible button example has styles (https://reakit.io/storybook/?path=/story/examples--accessible-button), but it's not on this PR (https://deploy-preview-781--reakit.netlify.app/storybook/?path=/story/button--accessible-button).

I think that's because styles are prefixed with an id in the [postcss.config.js](https://github.com/reakit/reakit/blob/master/.storybook/postcss.config.js) file so they're scoped to that specific example. The old stories file had a decorator wrapping the story with a div with the id so it works:

https://github.com/reakit/reakit/blob/0069ca70fb28ece1fee2c78ea70b035bd8ebcf24/.storybook/stories.js#L16-L22

I remember it was possible to add a global decorator on the storybook config. And I'm pretty sure that would solve the problem.

**Comment by david-szabo97** [comment]
Thanks for catching that! Should be all good now!

**Review by diegohaz — APPROVED** [review]
Awesome! Thanks! 💯

**Pull request merged**
