### PR TITLE
Setup Cypress

### LINKED ISSUE #624: Cross browser testing
Opened after #368 reappeared on Firefox, something that wouldn't have happened with some cross browser testing.

There was also a mention of performance testing too in https://github.com/reakit/reakit/issues/429#issue-490585539. This would be nice to have IMO but isn't as crucial as testing functionality testing in real browsers.

I've seen BrowserStack mentioned before, is this a good avenue to go down?

### PR DESCRIPTION
**Pull request by tom-sherman**
Resolves #624 

Opening up an early PR for this to discuss a few things.

- Is Cypress the right tool for the browser testing?
- I've chosen a folder structure from what I've gathered is Cypress best practices, but it may not be right for this project

### CODE REVIEW

**Comment by diegohaz** [comment]
Thanks for working on this @tom-sherman! ❤️

I would say cypress tests should live together with the current example tests, but with a different suffix (`-cypress` maybe?), and only in those examples which the current tests aren’t enough, like with animations or when there are differences across browsers.

**Comment by diegohaz** [comment]
By the way, what are your opinions about https://github.com/testing-library/cypress-testing-library?

**Comment by tom-sherman** [comment]
@diegohaz looks very useful, I'll add it in. The Cypress API is a bit funky compared to jest/testing lib hopefully this will help a bit.

**Comment by diegohaz** [comment]
Do you know if Cypress supports IE 11, Safari etc.? I couldn't find any information about this. Otherwise, I think it's worth it exploring Jest + Puppeteer + BrowserStack.

**Comment by tom-sherman** [comment]
It does not, list of available devices here: https://docs.cypress.io/guides/guides/launching-browsers.html#

We're probably better going with BrowserStack then I guess.

**Pull request closed without merging**
