### PR TITLE
feat: Upgrade to `styled-components` v4

### PR DESCRIPTION
**Pull request by diegohaz**

### CODE REVIEW

**Comment by stephen776** [comment]
When will this be released?

**Comment by PlayMa256** [comment]
ASAP, haz is rushing to finish this

**Comment by maciekgrzybek** [comment]
What's the status on that?

**Comment by diegohaz** [comment]
A beta version will be released today

**Comment by maciekgrzybek** [comment]
Perfect, thanks for quick response :)

**Comment by PlayMa256** [comment]
If you also find that reakit-codemods is not working properly make sure to open an issue so we can fix those transformations really fast!

**Comment by bvego** [comment]
Hi, any info on when v0.16 is getting out of the beta status? 😄

**Comment by stephen776** [comment]
Checking in for another update on when this is coming out of beta.

**Pull request merged**
